### ISSUE TITLE
Store grid with map rather than 2D vector

### ISSUE THREAD

**Issue by lpil** [redbadger/clojure-gol#2]
Hey!

If you store cells in maps where the coordinates are the keys you'll only have to iterate over each alive cell rather than all possible cells.

Also allows you to be a lot more flexible with the bounds of your game, if that's handy.

**Comment by charypar** [comment]
True, but for creation of cells, we need to detect empty cells with exactly three neighbours too... Not sure that's very easy in a map?

Suppose we could iterate over the neighbourhood of a live cell to look for empty cells matching the creation rules

**Comment by lpil** [comment]
Yee that's what I was thinking. You only need to check cells that are near living cells, so enumerating over the living cells works well for that too. Get that infinite board that the game is supposed to be played on :)

**Comment by charypar** [comment]
If/when we have a good way of visualising that, infinite board would be pretty cool. 

Is it reasonable to assume there will be a relative minority of live cells and so iterating over those is going to be faster than iterating through the entire grid, even though the size of the neighbourhood to operate on is now 3 times what it was...?

**Comment by lpil** [comment]
I imagine so. In my experience you need a pretty big board to get interesting patterns, and it's normally pretty empty. You can cache the alive checks too.

**Comment by lpil** [comment]
Benchmarks are the answer :D
